server {
    listen 80;
    server_name localhost;
    
    # serve static assets
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    
    # static probe endpoints
    location /healthz {
        access_log off;
        add_header 'Content-Type' 'text/plain';
        return 200 'OK';
    }
    
    location /status {
        access_log off;
        add_header 'Content-Type' 'text/plain';
        return 200 'Ready';
    }
}